export const configuration = {
  aggregations: {
    location: {
      title: 'location',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: true,
    },
    // pointOfView: {
    //   title: 'pointOfView',
    //   size: 10,
    //   sort: 'term',
    //   order: 'asc',
    //   conjunction: false,
    // },
    leftOfBicycleLane: {
      title: 'leftOfBicycleLane',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    divideLeftWidthName: {
      title: 'divideLeftWidthName',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    divideLeftWidth: {
      title: 'divideLeftWidth',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    divideLeftCategory: {
      title: 'divideLeftCategory',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    divideLeftStructural: {
      title: 'divideLeftStructural',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    leftOfBicycleLaneWithStructuralDivide: {
      title: 'leftOfBicycleLaneWithStructuralDivide',
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    bicycleLaneWidthName: {
      title: 'bicycleLaneWidthName',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    bicycleLaneWidth: {
      title: 'bicycleLaneWidth',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    divideRightWidthName: {
      title: 'divideRightWidthName',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    divideRightWidth: {
      title: 'divideRightWidth',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    divideRightCategory: {
      title: 'divideRightCategory',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    pavementWidthName: {
      title: 'pavementWidthName',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    pavementWidth: {
      title: 'pavementWidth',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    pavementHasShops: {
      title: 'pavementHasShops',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    bicycleLaneWidthUsable: {
      title: 'bicycleLaneWidthUsable',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    vehicleLaneUsage: {
      title: 'vehicleLaneUsage',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    vehicleLaneMaxspeed: {
      title: 'vehicleLaneMaxspeed',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    bicycleLaneLanes: {
      title: 'bicycleLaneLanes',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    bicycleLaneSurface: {
      title: 'bicycleLaneSurface',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    divideLeftMarking: {
      title: 'divideLeftMarking',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    divideRightMarking: {
      title: 'divideRightMarking',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    parkingCategory: {
      title: 'parkingCategory',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    rightOfBicycleLane: {
      title: 'rightOfBicycleLane',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    divideIsPhysical: {
      title: 'divideIsPhysical',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
    motorVehicleTrafficVolumen: {
      title: 'motorVehicleTrafficVolumen',
      size: 10,
      sort: 'term',
      order: 'asc',
      conjunction: false,
    },
  },
  searchableFields: [],
  native_search_enabled: false,
};
