export const primaryDomainHost = 'radwege-check.de'
export const primaryDomain = 'https://radwege-check.de'
export const englishDomainHostWitoutEnding = 'bikelane-safetycheck'
export const englishDomainHost = 'bikelane-safetycheck.net'
export const englishDomain = 'https://bikelane-safetycheck.net'
